name: Library Cache Builder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  env:
    LIBXML2_VERSION: 2.9.10
    ZLIB_VERSION: 1.2.12

  zlib:
    uses: ./.github/workflows/build-library.yml
    with:
      library_name: zlib
      repo_url: https://github.com/cmlibs-dependencies/zlib.git
      version: ${{ env.ZLIB_VERSION }}

  libxml2:
    needs: zlib
    uses: ./.github/workflows/build-library.yml
    with:
      library_name: libxml2
      repo_url: https://github.com/cmlibs-dependencies/libxml2.git
      version: ${{ env.LIBXML2_VERSION }}
      cmake_args: >-
        -DZLIB_DIR=${{ github.workspace }}/zlib/zlib/lib/cmake/ZLIB-${{ env.ZLIB_VERSION }}
        -DLIBXML2_WITH_DEBUG=OFF
        -DLIBXML2_WITH_ICONV=OFF
        -DLIBXML2_WITH_LEGACY=OFF
        -DLIBXML2_WITH_LZMA=OFF
        -DLIBXML2_WITH_MODULES=OFF
        -DLIBXML2_WITH_PROGRAMS=OFF
        -DLIBXML2_WITH_PYTHON=OFF
        -DLIBXML2_WITH_TESTS=OFF
