name: Library Cache Builder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zlib:
    uses: ./.github/workflows/build-library.yml
    with:
      library_name: zlib
      repo_url: https://github.com/cmlibs-dependencies/zlib.git
      version: '1.2.12'

  libxml2:
    needs: zlib
    uses: ./.github/workflows/build-library.yml
    with:
      library_name: libxml2
      repo_url: https://github.com/cmlibs-dependencies/libxml2.git
      version: '2.9.10'
      cmake_args: >-
        -DZLIB_DIR=${{ github.workspace }}/zlib/zlib/lib/cmake/ZLIB-1.2.12
        -DLIBXML2_WITH_DEBUG=OFF
        -DLIBXML2_WITH_ICONV=OFF
        -DLIBXML2_WITH_LEGACY=OFF
        -DLIBXML2_WITH_LZMA=OFF
        -DLIBXML2_WITH_MODULES=OFF
        -DLIBXML2_WITH_PROGRAMS=OFF
        -DLIBXML2_WITH_PYTHON=OFF
        -DLIBXML2_WITH_TESTS=OFF
