name: Library Cache Builder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  libraries:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Linux'
            os: ubuntu-latest
            build_shared_libs: 'OFF'
          #- name: 'Windows'
          #  os: windows-latest
          #  build_shared_libs: 'OFF'
          #- name: 'WASM'
          #  os: macos-latest
          #  emcmake: 'emcmake'
          #  build_shared_libs: 'OFF'
    env:
      LIBXML2_VERSION: 2.9.10
      ZLIB_VERSION: 1.2.12
    steps:
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Configure MSVC
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Emscripten
        if: ${{ matrix.name == 'WASM' }}
        run: |
          brew install --overwrite emscripten
      - name: Set lib_type based on matrix.build_shared_libs
        id: set-lib-type
        run: |
          if [ "${{ matrix.build_shared_libs }}" = "ON" ]; then
            echo "lib_type=Shared" >> $GITHUB_OUTPUT
          else
            echo "lib_type=Static" >> $GITHUB_OUTPUT
          fi
      - name: Build zlib
        run: |
          git clone -b v${{ env.ZLIB_VERSION }} --depth 1 https://github.com/cmlibs-dependencies/zlib.git
          cd zlib
          ${{ matrix.emcmake }} cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=zlib -DBUILD_SHARED_LIBS=${{ matrix.build_shared_libs }}
          cmake --build build
          cmake --install build
          tar -czf ../zlib-${{ matrix.name }}-${{ steps.set-lib-type.outputs.lib_type }}.tar.gz zlib
      - name: Build libxml2
        run: |
          git clone -b v${{ env.LIBXML2_VERSION }} --depth 1 https://github.com/cmlibs-dependencies/libxml2.git
          cd libxml2
          ${{ matrix.emcmake }} cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=libxml2 -DZLIB_DIR=${{ github.workspace }}/zlib/zlib/lib/cmake/ZLIB-${{ env.ZLIB_VERSION }} -DBUILD_SHARED_LIBS=${{ matrix.build_shared_libs }} -DLIBXML2_WITH_DEBUG=OFF -DLIBXML2_WITH_ICONV=OFF -DLIBXML2_WITH_LEGACY=OFF -DLIBXML2_WITH_LZMA=OFF -DLIBXML2_WITH_MODULES=OFF -DLIBXML2_WITH_PROGRAMS=OFF -DLIBXML2_WITH_PYTHON=OFF -DLIBXML2_WITH_TESTS=OFF
          cmake --build build
          cmake --install build
          tar -czf ../libxml2-${{ matrix.name }}.tar.gz libxml2
      - name: Release libxml2 and zlib
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/*.tar.gz
          tag_name: cache
