name: Super Build Library Cache Builder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'linux'
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Requirements
        run: |
          sudo apt install libosmesa6-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: Checkout Super Build
        run: |
          git clone -b main --depth 1 https://github.com/cmlibs/SuperBuild.git superbuild

      - name: Prepare Super Build
        run: |
          mkdir ${{ github.workspace }}/cmlibs

      - name: Configure Super Build
        run: |
          cd superbuild
          mkdir build
          cmake -G Ninja -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DCMLIBS_ROOT="${{ github.workspace }}/cmlibs" \
            -DCMLIBS_SETUP_TYPE=dependencies \
            -DCMLIBS_USE_MESA=TRUE

      - name: Build Super Build
        run: |
          cd superbuild/build
          cmake --build . --parallel 4

      - name: Create Archive
        run: |
          cd ${{ github.workspace }}/cmlibs
          tar -czf superbuild-osmesa-libs-${{ matrix.name }}.tar.gz install

      - name: Add Archive to Cache
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/superbuild-libs-${{ matrix.name }}.tar.gz
          tag_name: cache
